from __future__ import annotations

from typing import Protocol

from code_review.domain.auth_models import AuthSession, AuthUser, UserPage, UserStats


class AuthStorePort(Protocol):
    async def get_user_by_username(self, username: str) -> tuple[AuthUser, str] | None: ...
    async def get_user_by_id(self, user_id: str) -> AuthUser | None: ...
    async def get_session(self, token: str) -> tuple[AuthSession, AuthUser] | None: ...
    async def create_session(self, user_id: str, token: str, csrf_token: str) -> AuthSession: ...
    async def list_user_sessions(self, user_id: str) -> list[AuthSession]: ...
    async def revoke_user_sessions(self, user_id: str) -> None: ...
    async def revoke_session(self, token: str) -> None: ...
    async def verify_csrf(self, token: str, csrf_token: str) -> tuple[AuthSession, AuthUser] | None: ...
    async def create_user(self, username: str, password_hash: str) -> AuthUser: ...
    async def list_users(self, query: str | None, status: str, page: int, page_size: int) -> UserPage: ...
    async def user_stats(self) -> UserStats: ...
    async def set_user_active(self, user_id: str, active: bool) -> AuthUser: ...
    async def set_password(self, user_id: str, password_hash: str, must_change: bool) -> None: ...
    async def reset_user_password(self, user_id: str, password_hash: str) -> None: ...
    async def review_ids_for_owner(self, user_id: str) -> list[str]: ...
    async def delete_user_record(self, user_id: str) -> None: ...
